### PR TITLE
Rido Review to Change CLI article

### PR DESCRIPTION
**Pull request by rido-min**
Added a note to specify this is for Update5 and above
Better explain what VS does when add a plugin
Add a section to explain how to add a plugin specific version.

### CODE REVIEW

**Comment by kirupa** [comment]
## Validation Status: Successful ##


 JobID: 1782f1cc-1073-4961-a2bf-5224b0916e11

**Comment by kirupa** [comment]
## Articles to review
The articles impacted by this PR were staged review at: 

* [http://taco.visualstudio.com/en-us/docs/change-cli-version/](http://taco.visualstudio.com/en-us/docs/change-cli-version/?rnd=1)

**Comment by kirupa** [comment]
## Validation Status: Successful ##


 JobID: 5ec92ce8-9b8f-4619-ba7f-6c20a33664c5

**Comment by kirupa** [comment]
## Validation Status: Successful ##


 JobID: 8512268f-d2ba-439c-8d9b-3a28b3fff9ef

**Comment by kirupa** [comment]
## Articles to review
The articles impacted by this PR were staged review at: 

* [http://taco.visualstudio.com/en-us/docs/change-cli-version/](http://taco.visualstudio.com/en-us/docs/change-cli-version/?rnd=1)

**Comment by normesta** [comment]
Thx RIDO. I'll accept the PR but I plan to move the steps for updating plugin versions to the topic that we have about plugin management.

**Pull request merged**
