### PR TITLE
Updated get-started-first-mobile-app document

### PR DESCRIPTION
**Pull request by jrebagliatti**
- Added Cordova framework summary to document introduction section
- Removed JQuery NuGet package and added instructions to manually download the library
- Expanded Cordova project structure explanation in "Quick tour of the project" section
- Shortened "Fix and fix problems" by summarizing the VS debugging features
- Moved and expanded plugins explanation from "Find app settings" to "Access a device capability" section
- Moved app styles to a CSS file
- Expanded "Run your app" section by adding more information about emulators
- Updated sample app screenshots

The updates in the solution were sent in [this PR](https://github.com/Microsoft/cordova-samples/pull/29)

### CODE REVIEW

**Comment by kirupa** [comment]
## Validation Status: Errors ##


### Articles ###
| Article | Status | Details | 
|---|---|---|
| get-started-first-mobile-app.md | Failed | [Details](#get-started-first-mobile-app.md) |

<a name="get-started-first-mobile-app.md"></a>
#### [get-started-first-mobile-app.md](https://github.com/Microsoft/cordova-docs/blob/ebf4062e4c3d89c2e5ff6c3a0a3e8b31634f86ff/articles/getting-started/get-started-first-mobile-app.md) ####
* **[Error]** <code>ms.date</code> value '2/22/2016' has an invalid date. Format should be: mm/dd/yyyy (both month and day should be 2 digits)
 

 JobID: 260c210b-b39c-4a55-8c08-7a526ddd4c56

**Comment by kirupa** [comment]
## Validation Status: Successful ##


 JobID: 94a38764-e49a-4e27-8c33-d67e043d86d9

**Comment by kirupa** [comment]
## Articles to review
The articles impacted by this PR were staged review at: 

* [http://taco.visualstudio.com/en-us/docs/get-started-first-mobile-app/](http://taco.visualstudio.com/en-us/docs/get-started-first-mobile-app/?rnd=1)

**Comment by kirupa** [comment]
## Validation Status: Successful ##


 JobID: 7592d96f-9dd2-41e4-bfd4-bcca2c5c77da

**Comment by kirupa** [comment]
## Articles to review
The articles impacted by this PR were staged review at: 

* [http://taco.visualstudio.com/en-us/docs/get-started-first-mobile-app/](http://taco.visualstudio.com/en-us/docs/get-started-first-mobile-app/?rnd=1)

**Comment by kirupa** [comment]
## Validation Status: Successful ##


 JobID: 7f920734-0143-4974-9f4c-41f065f2e973

**Comment by kirupa** [comment]
## Articles to review
The articles impacted by this PR were staged review at: 

* [http://taco.visualstudio.com/en-us/docs/get-started-first-mobile-app/](http://taco.visualstudio.com/en-us/docs/get-started-first-mobile-app/?rnd=1)

**Comment by kirupa** [comment]
## Validation Status: Successful ##


 JobID: 642cc2b4-6133-402d-9571-626ed58636fd

**Comment by kirupa** [comment]
## Articles to review
The articles impacted by this PR were staged review at: 

* [http://taco.visualstudio.com/en-us/docs/get-started-first-mobile-app/](http://taco.visualstudio.com/en-us/docs/get-started-first-mobile-app/?rnd=1)

**Comment by kirupa** [comment]
## Validation Status: Successful ##


 JobID: a273f1ad-9a2b-44e5-96a5-df0cfc349e58

**Comment by kirupa** [comment]
## Articles to review
The articles impacted by this PR were staged review at: 

* [http://taco.visualstudio.com/en-us/docs/get-started-first-mobile-app/](http://taco.visualstudio.com/en-us/docs/get-started-first-mobile-app/?rnd=1)

**Comment by normesta** [comment]
Nice job. I'm going to modify a few things after I accept this PR, but the UI looks much better and the steps required to achieve that aren't overly complicated.

**Pull request merged**
