### PR TITLE
Updates to unit testing docs

### PR DESCRIPTION
**Pull request by kraigb**
Converted QUnit tests to Jasmine, and merges gulp task runner material into the basic unit testing topic so we can remove the separate Karma and Chutzpah topics from the toc.

### CODE REVIEW

**Comment by kirupa** [comment]
## Validation Status: Warnings ##


### Articles ###
| Article | Status | Details | 
|---|---|---|
| unit-test-02-environments.md | Warning | [Details](#unit-test-02-environments.md) |
| unit-test-03-basic-testing.md | Warning | [Details](#unit-test-03-basic-testing.md) |

<a name="unit-test-02-environments.md"></a>
#### [unit-test-02-environments.md](https://github.com/Microsoft/cordova-docs/blob/dbb61ed413b52d20c1434dd5744bd94f113e9cee/articles/test/unit-test-02-environments.md) ####
* **[Warning]** HTML scripts, styles or image tags are not a valid Markdown syntax. 0 script tags, 1 style tags and 0 image tags were found in the document content.
 
<a name="unit-test-03-basic-testing.md"></a>
#### [unit-test-03-basic-testing.md](https://github.com/Microsoft/cordova-docs/blob/dbb61ed413b52d20c1434dd5744bd94f113e9cee/articles/test/unit-test-03-basic-testing.md) ####
* **[Warning]** HTML scripts, styles or image tags are not a valid Markdown syntax. 0 script tags, 1 style tags and 0 image tags were found in the document content.
 

 JobID: 07ea057c-30cb-49c2-899a-5ae5880ef48b

**Comment by kirupa** [comment]
## Articles to review
The articles impacted by this PR were staged review at: 

* [http://taco.visualstudio.com/en-us/docs/unit-test-02-environments/](http://taco.visualstudio.com/en-us/docs/unit-test-02-environments/?rnd=1)
* [http://taco.visualstudio.com/en-us/docs/unit-test-03-basic-testing/](http://taco.visualstudio.com/en-us/docs/unit-test-03-basic-testing/?rnd=1)
* [http://taco.visualstudio.com/en-us/docs/unit-test-05-tdd/](http://taco.visualstudio.com/en-us/docs/unit-test-05-tdd/?rnd=1)
* [http://taco.visualstudio.com/en-us/docs/unit-test-06-debug/](http://taco.visualstudio.com/en-us/docs/unit-test-06-debug/?rnd=1)

**Comment by kraigb** [comment]
Are those the right staging links? They look like the live docs.

The warnings are because of HTML tables in the topics.

**Comment by ljzhong** [comment]
There is no staging for docs, there is only staging for website changes. I recommend you just merge in these changes and fix as needed.

**Pull request merged**
