### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kraigb**

### CODE REVIEW

**Comment by kirupa** [comment]
## Validation Status: Successful ##


 JobID: 09764753-2bdb-40c9-b8c7-5df4a241ee16

**Comment by kirupa** [comment]
## Articles to review
The articles impacted by this PR were staged review at: 

* [http://taco.visualstudio.com/en-us/docs/unit-test-01-primer/](http://taco.visualstudio.com/en-us/docs/unit-test-01-primer/?rnd=1)

**Comment by kraigb** [comment]
Reopening...trying to understand the process to get these few typos fixed. :)

**Comment by kirupa** [comment]
## Validation Status: Successful ##


 JobID: 0fbb9f05-4df4-457a-a76c-44b60003c2d0

**Comment by kirupa** [comment]
## Articles to review
The articles impacted by this PR were staged review at: 

* [http://taco.visualstudio.com/en-us/docs/unit-test-01-primer/](http://taco.visualstudio.com/en-us/docs/unit-test-01-primer/?rnd=1)

**Pull request merged**
