### PR TITLE
fixed code formatting in ui debug article

### PR DESCRIPTION
**Pull request by johnwargo**
In reviewing the material, I noticed that code formatting wasn't implemented correctly, so I fixed it.

### CODE REVIEW

**Comment by meganbradley** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C24%5Cf2153882-3fb7-a246-b84e-0fdb3ad073ec%5CPullRequest%5C201701241606289073-556%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kirupa** [comment]
## Validation Status: Errors ##


### Articles ###
| Article | Status | Details | 
|---|---|---|
| uitest-06-debugging.md | Failed | [Details](#uitest-06-debugging.md) |

<a name="uitest-06-debugging.md"></a>
#### [uitest-06-debugging.md](https://github.com/Microsoft/cordova-docs/blob/90cce4ee0b9c785b2bffa1259e97a225a6bbcd8c/articles/test-ui/uitest-06-debugging.md) ####
* **[Error]** The following tags were not recognized: ms.technology, ms.prod.
* **[Warning]** The article doesn't have a title (it's missing the H1 heading, coded in markdown as '# heading text'). Add a main title to the article right after the tags element.
 

 JobID: a719c1f0-6480-4784-9a22-97bce86fecd5

**Comment by meganbradley** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C24%5Cf2153882-3fb7-a246-b84e-0fdb3ad073ec%5CPullRequest%5C201701241615279476-556%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kirupa** [comment]
## Validation Status: Warnings ##


### Articles ###
| Article | Status | Details | 
|---|---|---|
| uitest-06-debugging.md | Warning | [Details](#uitest-06-debugging.md) |

<a name="uitest-06-debugging.md"></a>
#### [uitest-06-debugging.md](https://github.com/Microsoft/cordova-docs/blob/c25452ff38f917ffcc27fc148c657fe0a4eb5bf8/articles/test-ui/uitest-06-debugging.md) ####
* **[Warning]** The article doesn't have a title (it's missing the H1 heading, coded in markdown as '# heading text'). Add a main title to the article right after the tags element.
 

 JobID: ce13c33d-d7aa-4dbd-b768-2c5662e447b8

**Pull request merged**
