### PR TITLE
New "Visual Studio Code and Apache Cordova" document

### PR DESCRIPTION
**Pull request by jrebagliatti**
- Added new document: "Get started with Visual Studio Code and Apache Cordova"
- Similar to [get-started-first-mobile-app](https://github.com/Microsoft/cordova-docs/blob/master/articles/getting-started/get-started-first-mobile-app.md) but using [Cordova Tools extension](https://marketplace.visualstudio.com/items?itemName=vsmobile.cordova-tools)
- Visual Studio Code as IDE
- Screenshots using OS X
- Added @davidsalgado as author

### CODE REVIEW

**Comment by kirupa** [comment]
## Validation Status: Successful ##


 JobID: 91d9f67a-c470-455d-a38d-858385a18545

**Comment by kirupa** [comment]
## Articles to review
The articles impacted by this PR were staged review at: 

* [http://taco.visualstudio.com/en-us/docs/get-started-vs-code-cordova-tools-extension/](http://taco.visualstudio.com/en-us/docs/get-started-vs-code-cordova-tools-extension/?rnd=1)

**Comment by kirupa** [comment]
## Validation Status: Successful ##


 JobID: 858f8194-a6be-4908-8fa6-a32d5ec83876

**Comment by kirupa** [comment]
## Articles to review
The articles impacted by this PR were staged review at: 

* [http://taco.visualstudio.com/en-us/docs/get-started-vs-code-cordova-tools-extension/](http://taco.visualstudio.com/en-us/docs/get-started-vs-code-cordova-tools-extension/?rnd=1)

**Comment by kirupa** [comment]
## Validation Status: Successful ##


 JobID: 6dbf3d0a-3f66-42e0-9732-6e7ee8f20055

**Comment by kirupa** [comment]
## Articles to review
The articles impacted by this PR were staged review at: 

* [http://taco.visualstudio.com/en-us/docs/get-started-vs-code-cordova-tools-extension/](http://taco.visualstudio.com/en-us/docs/get-started-vs-code-cordova-tools-extension/?rnd=1)

**Comment by kirupa** [comment]
## Validation Status: Successful ##


 JobID: d56321f1-f7f7-4591-b46f-a760fbc53a53

**Comment by kirupa** [comment]
## Articles to review
The articles impacted by this PR were staged review at: 

* [http://taco.visualstudio.com/en-us/docs/get-started-vs-code-cordova-tools-extension/](http://taco.visualstudio.com/en-us/docs/get-started-vs-code-cordova-tools-extension/?rnd=1)

**Comment by kirupa** [comment]
## Validation Status: Successful ##


 JobID: 69719fda-10a1-4606-b397-b28336d5c8de

**Comment by kirupa** [comment]
## Articles to review
The articles impacted by this PR were staged review at: 

* [http://taco.visualstudio.com/en-us/docs/get-started-vs-code-cordova-tools-extension/](http://taco.visualstudio.com/en-us/docs/get-started-vs-code-cordova-tools-extension/?rnd=1)

**Comment by normesta** [comment]
Thanks for the contribution! Right now, we're only accepting articles that use VS as the IDE. For content where VS Code is the IDE, I suggest submitting a pull request to https://github.com/Microsoft/vscode-cordova. There is no front-end website for that github repo, but you could modify the extension readme to point to your article for visibility if you wanted to.

**Pull request closed without merging**
