### PR TITLE
fixed typo in step 5 of macincloud configuration.

### PR DESCRIPTION
**Pull request by johnwargo**

### CODE REVIEW

**Comment by meganbradley** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/getting-started/build_ios_cloud.md](https://github.com/Microsoft/cordova-docs/blob/johnwargo-patch-1/articles/getting-started/build_ios_cloud.md) | :white_check_mark:Succeeded | | [Details](#user-content-articles/getting-started/build_ios_cloud.md)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C9%5Cf2153882-3fb7-a246-b84e-0fdb3ad073ec%5CPullRequest%5C201611091738359274-547%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kirupa** [comment]
## Validation Status: Errors ##


### Articles ###
| Article | Status | Details | 
|---|---|---|
| build_ios_cloud.md | Failed | [Details](#build_ios_cloud.md) |

<a name="build_ios_cloud.md"></a>
#### [build_ios_cloud.md](https://github.com/Microsoft/cordova-docs/blob/28a52d68ae1245232f3c52bcfa16c9454d98bd08/articles/getting-started/build_ios_cloud.md) ####
* **[Error]** The following tags were not recognized: ms.technology, ms.prod.
* **[Warning]** The article name cannot contain uppercase letters, white spaces or special characters except from '-'.
 

 JobID: f27d9691-38c5-4136-bc5d-205cead6a9b2

**Comment by meganbradley** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/getting-started/build_ios_cloud.md](https://github.com/Microsoft/cordova-docs/blob/johnwargo-patch-1/articles/getting-started/build_ios_cloud.md) | :white_check_mark:Succeeded | | [Details](#user-content-articles/getting-started/build_ios_cloud.md)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C9%5Cf2153882-3fb7-a246-b84e-0fdb3ad073ec%5CPullRequest%5C201611091847078000-547%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kirupa** [comment]
## Validation Status: Errors ##


### Articles ###
| Article | Status | Details | 
|---|---|---|
| build_ios_cloud.md | Failed | [Details](#build_ios_cloud.md) |

<a name="build_ios_cloud.md"></a>
#### [build_ios_cloud.md](https://github.com/Microsoft/cordova-docs/blob/db723db59f1cd95d463fecab5c7e1a29d7227385/articles/getting-started/build_ios_cloud.md) ####
* **[Error]** The following tags were not recognized: ms.technology, ms.prod.
* **[Warning]** The article name cannot contain uppercase letters, white spaces or special characters except from '-'.
 

 JobID: a3ff02e3-da41-467d-b025-9d2c97f9b068

**Pull request merged**
